name: Check latest flutter tag

on:
  schedule:
    - cron: "30 4 * * *"
  workflow_dispatch:

jobs:

  check_tags:

    runs-on: ubuntu-latest

    steps:
      - name: Check latest tags
        run: |
          export LAST_FLUTTER_TAG = curl -s https://api.github.com/repos/flutter/flutter/git/refs/tags | jq 'map(.ref) | map(sub("refs/tags/"; "")) | .[] | select(. | endswith("pre") | not)' | tail -n 1
          export LAST_IMAGE_TAG = curl -s https://api.github.com/repos/tauu/flutter-windows-builder/git/refs/tags | jq 'map(.ref) | map(sub("refs/tags/"; "")) | .[] | select(. | endswith("pre") | not)' | tail -n 1
          echo "LAST_FLUTTER_TAG=$LAST_FLUTTER_TAG" >> $GITHUB_ENV
          echo "LAST_IMAGE_TAG=$LAST_IMAGE_TAG" >> $GITHUB_ENV
      - name: Create Tag
        uses: actions/github-script@v6
        if: ${{env.LAST_FLUTTER_TAG}} == ${{env.LAST_IMAGE_TAG}}
        with:
          script: |
            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${{env.LAST_FLUTTER_TAG}}`,
                sha: context.sha
            })
