name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:

  build-push-image:

    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build
        if: ${{ github.ref_name == 'main' }}
        run: |
                docker build -f Dockerfile -t tauu/flutter-windows-builder:latest .
      - name: Docker Build
        if: ${{ github.ref_type == 'tag' }}
        run: |
                docker build -f Dockerfile --build-arg FLUTTER_VERSION=${{github.ref_name}} -t tauu/flutter-windows-builder:${{github.ref_name}} .
      - name: Docker Push
        if: ${{ github.ref_name == 'main' }}
        run: |
                docker push tauu/flutter-windows-builder:latest
      - name: Docker Push
        if: ${{ github.ref_type == 'tag' }}
        run: |
                docker push tauu/flutter-windows-builder:${{github.ref_name}}
