name: Docker Image CI

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: false
      latest:
        type: boolean
        required: false
        default: false

jobs:

  build-push-image:

    runs-on: windows-2019

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker build latest
        if: ${{ inputs.version == '' }}
        run: |
                docker build -f Dockerfile -t tauu/flutter-windows-builder:latest .
      - name: docker build version tag
        if: ${{ inputs.version != '' && ! inputs.latest }}
        run: |
                docker build -f Dockerfile --build-arg FLUTTER_VERSION=${{inputs.version}} -t tauu/flutter-windows-builder:${{inputs.version}} .
      - name: docker build version and latest tag
        if: ${{ inputs.version != '' && inputs.latest }}
        run: |
                docker build -f Dockerfile --build-arg FLUTTER_VERSION=${{inputs.version}} -t tauu/flutter-windows-builder:${{inputs.version}} -t tauu/flutter-windows-builder:latest .
      - name: docker push all tag
        if: ${{ inputs.version != '' }}
        run: |
                docker push -a tauu/flutter-windows-builder
